services:
  website:
    image: ghcr.io/fdbs-de/fdbs-website:latest
    environment:
      - VIRTUAL_HOST=${WEBSITE_DOMAIN}
      - LETSENCRYPT_HOST=${WEBSITE_DOMAIN}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
      - NUXT_PUBLIC_BACKEND_URL=${APP_URL}
      - NUXT_PUBLIC_FRONTEND_URL=${FRONTEND_URL}
      - NUXT_PUBLIC_WEBSITE_URL=${WEBSITE_URL}
      - NUXT_PUBLIC_SCREENS_URL=${SCREENS_URL}
    networks:
      - helium
    restart: always